// packages/desktop/src/lib/components/AgentTrace.svelte
<script lang="ts">
  import { ChevronRight, Terminal, Search, Activity, Cpu } from 'lucide-svelte';

  interface Props {
    toolCalls?: any[];
    progressLogs?: { text: string; time: number }[];
    isStreaming?: boolean;
    reasoningContent?: string;
    durationMs?: number;
  }

  let { 
    toolCalls = [], 
    progressLogs = [], 
    isStreaming = false, 
    reasoningContent = '',
    durationMs = 0
  }: Props = $props();

  let isOpen = $state(false);
  let startTime = Date.now();
  let elapsedTime = $state(0);
  let intervalId: number | null = null;

  // Auto expand when streaming starts
  $effect(() => {
    if (isStreaming && (toolCalls.length > 0 || progressLogs.length > 0 || reasoningContent)) {
      isOpen = true;
    }
  });

  // Track time if streaming
  $effect(() => {
    if (isStreaming) {
      intervalId = setInterval(() => {
        elapsedTime = Math.floor((Date.now() - startTime) / 1000);
      }, 1000);
    } else {
      if (intervalId) clearInterval(intervalId);
    }
    
    return () => {
      if (intervalId) clearInterval(intervalId);
    };
  });

  const hasContent = $derived(toolCalls.length > 0 || progressLogs.length > 0 || reasoningContent);

  function getSummaryText() {
    if (isStreaming) {
      return `Working for ${elapsedTime}s`;
    }
    if (elapsedTime > 0) {
      return `Worked for ${elapsedTime}s`;
    }
    if (durationMs > 0) {
      return `Worked for ${Math.max(1, Math.round(durationMs / 1000))}s`;
    }
    if (progressLogs.length > 1) {
      const firstTime = progressLogs[0].time;
      const lastTime = progressLogs[progressLogs.length - 1].time;
      const seconds = Math.max(1, Math.round((lastTime - firstTime) / 1000));
      return `Worked for ${seconds}s`;
    }
    return `Completed`;
  }

  function getIconForStep(text: string) {
    const lower = text.toLowerCase();
    if (lower.includes('find') || lower.includes('search') || lower.includes('explored')) return 'search';
    if (lower.includes('ran') || lower.includes('running') || lower.includes('execute')) return 'terminal';
    if (lower.includes('thought')) return 'cpu';
    return 'activity';
  }

  // Merge history tool_calls into readable strings if progressLogs is empty
  const traces = $derived(() => {
    const result: string[] = [];
    
    if (progressLogs && progressLogs.length > 0) {
      progressLogs.forEach(log => {
        const cleanText = log.text.replace(/<[^>]*>?/gm, '').replace(/\*+/g, '').trim();
        if (cleanText) result.push(cleanText);
      });
    } else if (toolCalls && toolCalls.length > 0) {
      toolCalls.forEach(tool => {
        result.push(`Ran ${tool.function?.name || 'tool'}`);
      });
    }
    
    return result;
  });
</script>

{#if hasContent}
  <div class="-mb-1">
    <button
      onclick={() => isOpen = !isOpen}
      class="flex items-center gap-1.5 text-slate-500 hover:text-slate-700 dark:text-[#e5e5ea] dark:hover:text-gray-200 transition-colors cursor-pointer w-fit"
    >
      <span class="text-[13px] font-medium">
        {getSummaryText()}
      </span>
      <div class="transition-transform duration-200 flex items-center" style="transform: {isOpen ? 'rotate(180deg)' : 'rotate(0deg)'}">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg>
      </div>
    </button>
    
    {#if isOpen}
      <div class="mt-2 pl-4 ml-3 border-l-[1.5px] border-gray-100 dark:border-[#3a3a3c] flex flex-col gap-3 py-1">
        {#if reasoningContent}
          <div class="flex items-start gap-3 text-sm text-gray-600 dark:text-[#e5e5ea]">
            <Cpu size={15} class="text-pink-400 mt-0.5 flex-shrink-0" />
            <div class="flex-1">
              <span class="font-medium text-gray-700 dark:text-[#e5e5ea]">Thinking:</span>
              <p class="mt-1 text-[13px] leading-relaxed italic whitespace-pre-wrap">{reasoningContent}</p>
            </div>
          </div>
        {/if}
        
        {#each traces() as trace, idx}
          <div class="flex items-center gap-3 text-[14px] text-slate-500 dark:text-[#e5e5ea]">
            {#if getIconForStep(trace) === 'search'}
              <Search size={15} class="text-blue-400 stroke-[1.5]" />
            {:else if getIconForStep(trace) === 'terminal'}
              <Terminal size={15} class="text-green-500 stroke-[1.5]" />
            {:else if getIconForStep(trace) === 'cpu'}
              <Cpu size={15} class="text-pink-400 stroke-[1.5]" />
            {:else}
              <Activity size={15} class="text-gray-400 stroke-[1.5]" />
            {/if}
            <span class="font-medium">{trace}</span>
          </div>
        {/each}
        
        {#if isStreaming}
          <div class="flex items-center gap-3 text-[14px] text-slate-500 dark:text-[#e5e5ea]">
            <Activity size={15} class="text-gray-400 animate-pulse stroke-[1.5]" />
            <span class="animate-pulse font-medium working-dots">Working</span>
          </div>
        {/if}
      </div>
    {/if}
  </div>
{/if}

// packages/dashboard/src/AgentTrace.tsx
import React, { useState, useEffect } from 'react';
import { ChevronRight, Terminal, Search, Activity, Cpu } from 'lucide-react';

export interface ProgressLog {
  text: string;
  time: number;
}

export interface AgentTraceProps {
  toolCalls?: any[];
  progressLogs?: ProgressLog[];
  isStreaming?: boolean;
  reasoningContent?: string;
  durationMs?: number;
}

export const AgentTrace: React.FC<AgentTraceProps> = ({ toolCalls = [], progressLogs = [], isStreaming = false, reasoningContent = '', durationMs = 0 }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [startTime] = useState<number>(Date.now());
  const [elapsedTime, setElapsedTime] = useState<number>(0);

  // Auto expand when streaming starts
  useEffect(() => {
    if (isStreaming && (toolCalls.length > 0 || progressLogs.length > 0 || reasoningContent)) {
      setIsOpen(true);
    }
  }, [isStreaming, reasoningContent]);

  // Track time if streaming
  useEffect(() => {
    if (!isStreaming) return;
    const interval = setInterval(() => {
      setElapsedTime(Math.floor((Date.now() - startTime) / 1000));
    }, 1000);
    return () => clearInterval(interval);
  }, [isStreaming, startTime]);

  const hasContent = toolCalls.length > 0 || progressLogs.length > 0 || !!reasoningContent;
  
  if (!hasContent) {
    return null;
  }

  const getSummaryText = () => {
    if (isStreaming) {
      return `Working for ${elapsedTime}s`;
    }
    if (elapsedTime > 0) {
      return `Worked for ${elapsedTime}s`;
    }
    if (durationMs > 0) {
      return `Worked for ${Math.max(1, Math.round(durationMs / 1000))}s`;
    }
    if (progressLogs && progressLogs.length > 1) {
      const firstTime = progressLogs[0].time;
      const lastTime = progressLogs[progressLogs.length - 1].time;
      const seconds = Math.max(1, Math.round((lastTime - firstTime) / 1000));
      return `Worked for ${seconds}s`;
    }
    return `Completed`;
  };

  const getIconForStep = (text: string) => {
    const lower = text.toLowerCase();
    if (lower.includes('find') || lower.includes('search') || lower.includes('explored')) return <Search size={14} color="#60a5fa" />;
    if (lower.includes('ran') || lower.includes('running') || lower.includes('execute')) return <Terminal size={14} color="#34d399" />;
    if (lower.includes('thought')) return <Cpu size={14} color="#f472b6" />;
    return <Activity size={14} color="#94a3b8" />;
  };

  // Merge history tool_calls into readable strings if progressLogs is empty
  const traces: string[] = [];
  
  if (progressLogs && progressLogs.length > 0) {
    // Clean up html tags in progress logs and add to traces
    progressLogs.forEach(log => {
      const cleanText = log.text.replace(/<[^>]*>?/gm, '').replace(/\*+/g, '').trim();
      if (cleanText) traces.push(cleanText);
    });
  } else if (toolCalls && toolCalls.length > 0) {
    toolCalls.forEach(tool => {
      traces.push(`Ran ${tool.function?.name || 'tool'}`);
    });
  }

  return (
    <div className="agent-trace-container" style={{ marginBottom: 0 }}>
      <div 
        className="agent-trace-header" 
        onClick={() => setIsOpen(!isOpen)}
        style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', padding: '4px 10px', borderRadius: '6px', width: 'fit-content' }}
      >
        <div className="agent-trace-summary" style={{ fontSize: '0.85rem', fontWeight: 500 }}>
          {getSummaryText()}
        </div>
        <div className="agent-trace-chevron" style={{ transform: isOpen ? 'rotate(90deg)' : 'rotate(0deg)', transition: 'transform 0.2s', display: 'flex' }}>
          <ChevronRight size={14} className="agent-trace-icon" />
        </div>
      </div>
      
      {isOpen && (
        <div className="agent-trace-body" style={{ marginTop: '8px', paddingLeft: '14px', marginLeft: '12px', display: 'flex', flexDirection: 'column', gap: '6px', borderLeft: '1.5px solid var(--border-color)', paddingBottom: '4px' }}>
          {reasoningContent && (
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px', fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
              <Cpu size={15} color="#f472b6" style={{ marginTop: '2px', flexShrink: 0 }} />
              <div style={{ flex: 1 }}>
                <span style={{ fontWeight: 500, color: 'var(--text-primary)' }}>Thinking:</span>
                <p style={{ marginTop: '4px', fontStyle: 'italic', whiteSpace: 'pre-wrap', lineHeight: 1.5 }}>
                  {reasoningContent}
                </p>
              </div>
            </div>
          )}
          {traces.map((trace, idx) => (
            <div key={idx} className="trace-item" style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem' }}>
              {getIconForStep(trace)}
              <span>{trace}</span>
            </div>
          ))}
          {isStreaming && (
            <div className="trace-item" style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem' }}>
              <span className="working-dots">Working</span>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
