// packages/dashboard/src/ExternalSkills.tsx
import { apiFetch } from './utils/api';
import React, { useState, useEffect } from 'react';
import { Plug, Compass, Search, Terminal, Zap, ArrowRightLeft, RefreshCw, Image, MapPin, User, Shield, PieChart, LineChart, WalletCards, Target, Droplet, Lock, Vault, Landmark, Flame, Send, Wallet } from 'lucide-react';

interface SkillParam {
  type: string;
  description?: string;
  enum?: string[];
}

interface SkillDefinition {
  type: string;
  isActive?: boolean;
  function: {
    name: string;
    description: string;
    parameters: {
      type: string;
      properties: Record<string, SkillParam>;
      required: string[];
    };
  };
}

const formatSkillName = (name: string) => {
  return name
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

const getSkillIcon = (skillName: string, isActive: boolean) => {
  const color = isActive !== false ? "var(--accent)" : "var(--tool-bg)";
  const size = 20;
  return <Plug size={size} color={color} />;
};

const ExternalSkills: React.FC = () => {
  const [skills, setSkills] = useState<SkillDefinition[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchSkills = async () => {
      try {
        const res = await apiFetch('/api/skills/external');
        if (res.ok) setSkills(await res.json());
      } catch (e) {
        console.error(e);
      } finally {
        setIsLoading(false);
      }
    };
    fetchSkills();
  }, []);

  const handleToggle = async (skillName: string, currentStatus: boolean) => {
    const newStatus = !currentStatus;
    
    // Optimistic UI update
    setSkills(prev => prev.map(s => 
      s.function.name === skillName ? { ...s, isActive: newStatus } : s
    ));

    try {
      await apiFetch('/api/skills/toggle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ skillName, active: newStatus })
      });
    } catch (e) {
      // Revert on error
      setSkills(prev => prev.map(s => 
        s.function.name === skillName ? { ...s, isActive: currentStatus } : s
      ));
      console.error('Failed to toggle skill', e);
    }
  };

  if (isLoading) return <div className="settings-subpanel">Loading skills...</div>;

  const filteredSkills = skills.filter(skill => 
    skill.function.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    skill.function.description.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="settings-subpanel">
      <div className="overview-header" style={{ marginBottom: '24px' }}>
        <h1 style={{ color: 'var(--text-primary)' }}>External Skills</h1>
        <p style={{ color: 'var(--text-secondary)' }}>User-installed third-party agent skills and custom integrations.</p>
      </div>

      <div style={{ 
        display: 'flex', 
        alignItems: 'center', 
        background: 'rgba(46, 52, 64, 0.4)', 
        border: '1px solid rgba(216, 222, 233, 0.1)', 
        borderRadius: '8px', 
        padding: '0 16px',
        marginBottom: '24px'
      }}>
        <Search size={18} color="#9ca3af" />
        <input 
          type="text" 
          placeholder="Filter installed external skills..." 
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          style={{ 
            background: 'transparent', 
            border: 'none', 
            outline: 'none', 
            color: 'var(--text-primary)', 
            padding: '16px', 
            width: '100%',
            fontSize: '0.95rem'
          }}
        />
        <span style={{ color: '#6b7280', fontSize: '0.85rem' }}>{filteredSkills.length} shown</span>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        {filteredSkills.map((skill, idx) => (
          <div key={idx} style={{ 
            display: 'flex', 
            alignItems: 'center', 
            justifyContent: 'space-between',
            background: 'var(--bg-sidebar)',
            padding: '20px 24px',
            borderRadius: '8px',
            border: '1px solid rgba(216, 222, 233, 0.05)'
          }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '16px', flex: 1 }}>
              <div style={{ marginTop: '2px' }}>
                {getSkillIcon(skill.function.name, skill.isActive !== false)}
              </div>
              <div>
                <h3 style={{ margin: '0 0 6px 0', fontSize: '1rem', color: skill.isActive !== false ? 'var(--text-primary)' : 'var(--text-secondary)', fontWeight: 600 }}>
                  {formatSkillName(skill.function.name)}
                </h3>
                <p style={{ margin: 0, color: '#9ca3af', fontSize: '0.85rem', lineHeight: '1.5', maxWidth: '800px' }}>
                  {skill.function.description}
                </p>
              </div>
            </div>
            
            <div style={{ marginLeft: '24px' }}>
              <button 
                onClick={() => handleToggle(skill.function.name, skill.isActive !== false)}
                style={{
                  position: 'relative',
                  width: '40px',
                  height: '22px',
                  borderRadius: '11px',
                  background: skill.isActive !== false ? 'var(--accent)' : 'var(--tool-bg)',
                  border: 'none',
                  cursor: 'pointer',
                  transition: 'background 0.3s ease',
                  padding: 0
                }}
              >
                <div style={{
                  position: 'absolute',
                  top: '2px',
                  left: skill.isActive !== false ? '20px' : '2px',
                  width: '18px',
                  height: '18px',
                  borderRadius: '50%',
                  background: '#fff',
                  transition: 'left 0.3s cubic-bezier(0.4, 0.0, 0.2, 1)',
                  boxShadow: '0 1px 3px rgba(0,0,0,0.3)'
                }} />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ExternalSkills;

// packages/desktop/src/lib/components/settings/ExternalSkills.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Plug, Search } from '@lucide/svelte';
  import { apiFetch } from '$lib/utils/api';

  interface SkillParam {
    type: string;
    description?: string;
    enum?: string[];
  }

  interface SkillDefinition {
    type: string;
    isActive?: boolean;
    function: {
      name: string;
      description: string;
      parameters: {
        type: string;
        properties: Record<string, SkillParam>;
        required: string[];
      };
    };
  }

  let skills = $state<SkillDefinition[]>([]);
  let searchQuery = $state('');
  let isLoading = $state(true);

  onMount(async () => {
    try {
      const res = await apiFetch('/api/skills/external');
      if (res.ok) {
        skills = await res.json();
      }
    } catch (e) {
      console.error(e);
    } finally {
      isLoading = false;
    }
  });

  function formatSkillName(name: string) {
    return name
      .split('_')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  async function handleToggle(skillName: string, currentStatus: boolean) {
    const newStatus = !currentStatus;
    
    // Optimistic UI update
    skills = skills.map(s => 
      s.function.name === skillName ? { ...s, isActive: newStatus } : s
    );

    try {
      await apiFetch('/api/skills/toggle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ skillName, active: newStatus })
      });
    } catch (e) {
      // Revert on error
      skills = skills.map(s => 
        s.function.name === skillName ? { ...s, isActive: currentStatus } : s
      );
      console.error('Failed to toggle skill', e);
    }
  }

  let filteredSkills = $derived(
    skills.filter(skill => 
      skill.function.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      skill.function.description.toLowerCase().includes(searchQuery.toLowerCase())
    )
  );
</script>

{#if isLoading}
  <div class="text-gray-500 p-8 text-center text-sm">Loading external skills...</div>
{:else}
  <div class="space-y-8 w-full">
    <div>
      <h2 class="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-1">External Skills</h2>
      <p class="text-sm text-gray-500 dark:text-gray-400 mb-6">User-installed third-party agent skills and custom integrations.</p>

      <div class="flex items-center bg-gray-50 dark:bg-[#27272a]/50 border border-gray-200 dark:border-white/10 rounded-xl px-4 mb-6 focus-within:ring-1 focus-within:ring-blue-500 transition-shadow">
        <Search size={18} class="text-gray-400" />
        <input 
          type="text" 
          placeholder="Filter installed external skills..." 
          bind:value={searchQuery}
          class="flex-1 bg-transparent border-none outline-none text-gray-900 dark:text-gray-100 py-3.5 px-3 text-[0.95rem] placeholder-gray-400"
        />
        <span class="text-gray-500 text-[0.85rem]">{filteredSkills.length} shown</span>
      </div>

      <div class="space-y-2.5">
        {#each filteredSkills as skill (skill.function.name)}
          {@const isActive = skill.isActive !== false}
          {@const formattedName = formatSkillName(skill.function.name)}
          
          <div class="flex items-center justify-between bg-white dark:bg-[#18181b]/50 p-5 rounded-xl border border-gray-200 dark:border-white/5 shadow-sm transition-colors {isActive ? 'border-gray-300 dark:border-white/10' : ''}">
            <div class="flex items-start gap-4 flex-1">
              <div class="mt-0.5">
                <Plug size={20} class={isActive ? 'text-blue-500' : 'text-gray-400'} />
              </div>
              <div>
                <h3 class="m-0 mb-1.5 text-[1rem] font-semibold {isActive ? 'text-gray-900 dark:text-gray-100' : 'text-gray-500'}">
                  {formattedName}
                </h3>
                <p class="m-0 text-gray-500 dark:text-gray-400 text-[0.85rem] leading-relaxed max-w-[800px]">
                  {skill.function.description}
                </p>
              </div>
            </div>
            
            <div class="ml-6 flex-shrink-0">
              <button 
                onclick={() => handleToggle(skill.function.name, isActive)}
                class="relative w-10 h-5.5 rounded-full border-none cursor-pointer transition-colors duration-300 p-0 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:focus:ring-offset-[#18181b] {isActive ? 'bg-blue-500' : 'bg-gray-300 dark:bg-gray-700'}"
              >
                <div class="absolute top-[2px] w-[18px] h-[18px] rounded-full bg-white shadow-sm transition-all duration-300 ease-[cubic-bezier(0.4,0,0.2,1)] {isActive ? 'left-[20px]' : 'left-[2px]'}"></div>
              </button>
            </div>
          </div>
        {/each}
      </div>
    </div>
  </div>
{/if}
