// packages/dashboard/src/Playbooks.tsx
import React, { useState, useEffect } from 'react';
import { apiFetch } from './utils/api';
import { BookOpen, Plus, Save, Trash2, Code, FileText, AlertTriangle, Folder, ChevronDown, ChevronRight } from 'lucide-react';
import './index.css';

interface Playbook {
  filename: string;
  content: string;
}

const Playbooks: React.FC = () => {
  const [playbooks, setPlaybooks] = useState<Playbook[]>([]);
  const [selectedFilename, setSelectedFilename] = useState<string | null>(null);
  const [editContent, setEditContent] = useState<string>('');
  const [newFilename, setNewFilename] = useState<string>('');
  const [isCreating, setIsCreating] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [expandedFolders, setExpandedFolders] = useState<Record<string, boolean>>({});

  const toggleFolder = (folder: string) => {
    setExpandedFolders(prev => ({ ...prev, [folder]: !prev[folder] }));
  };

  const groupedPlaybooks = playbooks.reduce((acc, p) => {
    const parts = p.filename.split(/[/\\]/); // Support both slashes
    const isRoot = parts.length === 1;
    const folder = isRoot ? 'Root' : parts[0];
    const label = isRoot ? parts[0] : parts.slice(1).join('/');
    
    if (!acc[folder]) acc[folder] = [];
    acc[folder].push({ ...p, label });
    return acc;
  }, {} as Record<string, (Playbook & { label: string })[]>);

  // Auto-expand folder of selected file when it changes
  useEffect(() => {
    if (selectedFilename && !isCreating) {
      const parts = selectedFilename.split(/[/\\]/);
      if (parts.length > 1) {
        setExpandedFolders(prev => ({ ...prev, [parts[0]]: true }));
      }
    }
  }, [selectedFilename, isCreating]);

  useEffect(() => {
    fetchPlaybooks();
  }, []);

  const fetchPlaybooks = async () => {
    setIsLoading(true);
    try {
      const res = await apiFetch('/api/playbooks');
      if (res.ok) {
        const data = await res.json();
        setPlaybooks(data || []);
        if (data && data.length > 0 && !selectedFilename && !isCreating) {
          handleSelect(data[0]);
        }
      }
    } catch (err) {
      console.error("Failed to fetch playbooks", err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSelect = (p: Playbook) => {
    setSelectedFilename(p.filename);
    setEditContent(p.content);
    setIsCreating(false);
  };

  const handleCreateNew = () => {
    setIsCreating(true);
    setSelectedFilename(null);
    setNewFilename('my-new-skill.md');
    setEditContent('---\nname: my-new-skill\ndescription: "Description here"\n---\n\n# Instructions\n\n1. Run command `...`\n');
  };

  const handleSave = async () => {
    const targetFilename = isCreating ? newFilename : selectedFilename;
    if (!targetFilename) return;
    
    try {
      await apiFetch('/api/playbooks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ filename: targetFilename, content: editContent })
      });
      await fetchPlaybooks();
      if (isCreating) {
        setIsCreating(false);
        setSelectedFilename(targetFilename);
      }
    } catch (err) {
      console.error("Failed to save playbook", err);
      alert("Failed to save playbook.");
    }
  };

  const handleDelete = async (filename: string) => {
    if (!confirm(`Are you sure you want to delete ${filename}?`)) return;
    try {
      await apiFetch(`/api/playbooks?filename=${encodeURIComponent(filename)}`, {
        method: 'DELETE'
      });
      setSelectedFilename(null);
      await fetchPlaybooks();
    } catch (err) {
      console.error("Failed to delete playbook", err);
      alert("Failed to delete playbook.");
    }
  };

  return (
    <div style={{ display: 'flex', height: '100%', width: '100%', overflow: 'hidden' }}>
      {/* Left Sidebar */}
      <div style={{ width: '300px', borderRight: '1px solid var(--border-color)', display: 'flex', flexDirection: 'column', backgroundColor: 'var(--panel-bg)' }}>
        <div style={{ padding: '15px', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 600 }}>
            <BookOpen size={18} /> Skill Store
          </div>
          <button onClick={handleCreateNew} style={{ background: 'transparent', border: 'none', color: 'var(--accent-color)', cursor: 'pointer', padding: '4px' }} title="New Playbook">
            <Plus size={18} />
          </button>
        </div>
        <div className="styled-scroll" style={{ flex: 1, overflowY: 'auto', padding: '10px 0' }}>
          {isLoading && playbooks.length === 0 ? (
            <div style={{ padding: '15px', textAlign: 'center', opacity: 0.5 }}>Loading...</div>
          ) : (
            Object.entries(groupedPlaybooks)
              .sort((a, b) => a[0].localeCompare(b[0]))
              .map(([folder, items]) => {
                const isExpanded = expandedFolders[folder] === true; // Default to false
                return (
                  <div key={folder} style={{ marginBottom: '2px' }}>
                    <div 
                      onClick={() => toggleFolder(folder)}
                      style={{ 
                        padding: '8px 15px', 
                        cursor: 'pointer', 
                        display: 'flex', 
                        alignItems: 'center', 
                        gap: '8px',
                        color: 'var(--text-secondary)',
                        fontWeight: 600,
                        fontSize: '12px',
                        textTransform: 'uppercase',
                        letterSpacing: '0.5px',
                        userSelect: 'none'
                      }}
                    >
                      {isExpanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                      <Folder size={14} />
                      <span style={{ flex: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                        {folder} ({items.length})
                      </span>
                    </div>
                    
                    {isExpanded && (
                      <div style={{ display: 'flex', flexDirection: 'column' }}>
                        {items.map(p => {
                          const isSelected = selectedFilename === p.filename && !isCreating;
                          return (
                            <div 
                              key={p.filename} 
                              onClick={() => handleSelect(p)}
                              style={{
                                padding: '8px 15px 8px 38px',
                                cursor: 'pointer',
                                backgroundColor: isSelected ? 'var(--highlight-bg, rgba(255,255,255,0.05))' : 'transparent',
                                borderLeft: isSelected ? '3px solid var(--accent-color)' : '3px solid transparent',
                                display: 'flex',
                                alignItems: 'center',
                                gap: '8px',
                                color: isSelected ? 'var(--text-primary)' : 'var(--text-secondary)',
                                fontSize: '13px',
                                transition: 'all 0.2s ease',
                                userSelect: 'none'
                              }}
                              title={p.filename}
                            >
                              <FileText size={14} opacity={isSelected ? 1 : 0.6} style={{ flexShrink: 0 }} />
                              <span style={{ 
                                whiteSpace: 'nowrap', 
                                overflow: 'hidden', 
                                textOverflow: 'ellipsis',
                                flex: 1
                              }}>
                                {p.label}
                              </span>
                            </div>
                          );
                        })}
                      </div>
                    )}
                  </div>
                );
              })
          )}
        </div>
      </div>

      {/* Right Editor */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', backgroundColor: 'var(--bg-color)' }}>
        {(selectedFilename || isCreating) ? (
          <>
            <div style={{ padding: '15px 20px', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flex: 1 }}>
                <Code size={18} opacity={0.7} />
                {isCreating ? (
                  <input 
                    value={newFilename}
                    onChange={(e) => setNewFilename(e.target.value)}
                    placeholder="e.g. custom-skill.md"
                    style={{ flex: 1, maxWidth: '300px', padding: '6px 10px', background: 'var(--input-bg)', border: '1px solid var(--border-color)', color: 'var(--text-primary)', borderRadius: '4px' }}
                  />
                ) : (
                  <span style={{ fontWeight: 600 }}>{selectedFilename}</span>
                )}
              </div>
              <div style={{ display: 'flex', gap: '10px' }}>
                {!isCreating && selectedFilename && (
                  <button 
                    onClick={() => handleDelete(selectedFilename)}
                    style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '6px 12px', background: 'transparent', border: '1px solid #ff4444', color: '#ff4444', borderRadius: '4px', cursor: 'pointer' }}
                  >
                    <Trash2 size={14} /> Delete
                  </button>
                )}
                <button 
                  onClick={handleSave}
                  style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '6px 16px', background: 'var(--accent-color)', border: 'none', color: '#fff', borderRadius: '4px', cursor: 'pointer', fontWeight: 500 }}
                >
                  <Save size={14} /> Save
                </button>
              </div>
            </div>
            <div style={{ flex: 1, padding: '20px', display: 'flex', flexDirection: 'column' }}>
              <div style={{ marginBottom: '10px', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '13px', color: 'var(--text-secondary)' }}>
                <AlertTriangle size={14} color="#f39c12" />
                Playbooks are written in Markdown. Nyxora reads these instructions to execute terminal commands autonomously.
              </div>
              <textarea
                className="styled-scroll"
                value={editContent}
                onChange={(e) => setEditContent(e.target.value)}
                style={{
                  flex: 1,
                  width: '100%',
                  resize: 'none',
                  padding: '15px',
                  fontFamily: 'monospace',
                  fontSize: '14px',
                  lineHeight: '1.5',
                  background: 'var(--input-bg)',
                  color: 'var(--text-primary)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '6px',
                  outline: 'none'
                }}
              />
            </div>
          </>
        ) : (
          <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', color: 'var(--text-secondary)' }}>
            <BookOpen size={48} opacity={0.2} style={{ marginBottom: '16px' }} />
            <h3>Select a Playbook</h3>
            <p>Or create a new one to teach Nyxora new skills.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default Playbooks;

// packages/desktop/src/lib/components/settings/Playbooks.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { apiFetch } from '$lib/utils/api';
  import { BookOpen, Plus, Save, Trash2, Code, FileText, AlertTriangle, Folder, ChevronDown, ChevronRight } from '@lucide/svelte';

  interface Playbook {
    filename: string;
    content: string;
  }

  let playbooks = $state<Playbook[]>([]);
  let selectedFilename = $state<string | null>(null);
  let editContent = $state<string>('');
  let newFilename = $state<string>('');
  let isCreating = $state(false);
  let isLoading = $state(false);
  let expandedFolders = $state<Record<string, boolean>>({});

  function toggleFolder(folder: string) {
    expandedFolders[folder] = !expandedFolders[folder];
  }

  let groupedPlaybooks = $derived(() => {
    return playbooks.reduce((acc, p) => {
      const parts = p.filename.split(/[/\\]/); // Support both slashes
      const isRoot = parts.length === 1;
      const folder = isRoot ? 'Root' : parts[0];
      const label = isRoot ? parts[0] : parts.slice(1).join('/');
      
      if (!acc[folder]) acc[folder] = [];
      acc[folder].push({ ...p, label });
      return acc;
    }, {} as Record<string, (Playbook & { label: string })[]>);
  });

  // Auto-expand folder of selected file when it changes
  $effect(() => {
    if (selectedFilename && !isCreating) {
      const parts = selectedFilename.split(/[/\\]/);
      if (parts.length > 1 && !expandedFolders[parts[0]]) {
        expandedFolders[parts[0]] = true;
      }
    }
  });

  onMount(() => {
    fetchPlaybooks();
  });

  async function fetchPlaybooks() {
    isLoading = true;
    try {
      const res = await apiFetch('/api/playbooks');
      if (res.ok) {
        const data = await res.json();
        playbooks = data || [];
        if (playbooks.length > 0 && !selectedFilename && !isCreating) {
          handleSelect(playbooks[0]);
        }
      }
    } catch (err) {
      console.error("Failed to fetch playbooks", err);
    } finally {
      isLoading = false;
    }
  }

  function handleSelect(p: Playbook) {
    selectedFilename = p.filename;
    editContent = p.content;
    isCreating = false;
  }

  function handleCreateNew() {
    isCreating = true;
    selectedFilename = null;
    newFilename = 'my-new-skill.md';
    editContent = '---\nname: my-new-skill\ndescription: "Description here"\n---\n\n# Instructions\n\n1. Run command `...`\n';
  }

  async function handleSave() {
    const targetFilename = isCreating ? newFilename : selectedFilename;
    if (!targetFilename) return;
    
    try {
      await apiFetch('/api/playbooks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ filename: targetFilename, content: editContent })
      });
      await fetchPlaybooks();
      if (isCreating) {
        isCreating = false;
        selectedFilename = targetFilename;
      }
    } catch (err) {
      console.error("Failed to save playbook", err);
      alert("Failed to save playbook.");
    }
  }

  async function handleDelete(filename: string) {
    if (!confirm(`Are you sure you want to delete ${filename}?`)) return;
    try {
      await apiFetch(`/api/playbooks?filename=${encodeURIComponent(filename)}`, {
        method: 'DELETE'
      });
      selectedFilename = null;
      await fetchPlaybooks();
    } catch (err) {
      console.error("Failed to delete playbook", err);
      alert("Failed to delete playbook.");
    }
  }
</script>

<div class="flex h-[72vh] w-full overflow-hidden rounded-xl border border-gray-200 dark:border-white/10 bg-white dark:bg-[#18181b]/50 shadow-sm">
  <!-- Left Sidebar -->
  <div class="w-[280px] border-r border-gray-200 dark:border-white/10 flex flex-col bg-gray-50 dark:bg-[#27272a]/30">
    <div class="p-4 border-b border-gray-200 dark:border-white/10 flex justify-between items-center bg-white dark:bg-transparent">
      <div class="flex items-center gap-2 font-semibold text-gray-800 dark:text-gray-200">
        <BookOpen size={18} class="text-blue-500" /> Skill Store
      </div>
      <button 
        onclick={handleCreateNew} 
        class="text-blue-500 hover:text-blue-600 dark:hover:text-blue-400 p-1 rounded-md hover:bg-blue-50 dark:hover:bg-blue-500/10 transition-colors" 
        title="New Playbook"
      >
        <Plus size={18} />
      </button>
    </div>
    
    <div class="flex-1 overflow-y-auto p-2">
      {#if isLoading && playbooks.length === 0}
        <div class="p-4 text-center text-gray-500 text-sm">Loading...</div>
      {:else}
        {#each Object.entries(groupedPlaybooks()).sort((a, b) => a[0].localeCompare(b[0])) as [folder, items] (folder)}
          {@const isExpanded = expandedFolders[folder] === true}
          <div class="mb-1">
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <div 
              onclick={() => toggleFolder(folder)}
              class="px-3 py-2 cursor-pointer flex items-center gap-2 text-gray-500 dark:text-gray-400 font-semibold text-xs uppercase tracking-wide hover:bg-gray-200/50 dark:hover:bg-white/5 rounded-md transition-colors select-none"
            >
              {#if isExpanded}
                <ChevronDown size={14} />
              {:else}
                <ChevronRight size={14} />
              {/if}
              <Folder size={14} class="text-gray-400" />
              <span class="flex-1 whitespace-nowrap overflow-hidden text-ellipsis">
                {folder} ({items.length})
              </span>
            </div>
            
            {#if isExpanded}
              <div class="flex flex-col mt-0.5">
                {#each items as p (p.filename)}
                  {@const isSelected = selectedFilename === p.filename && !isCreating}
                  <!-- svelte-ignore a11y_click_events_have_key_events -->
                  <!-- svelte-ignore a11y_no_static_element_interactions -->
                  <div 
                    onclick={() => handleSelect(p)}
                    class="pl-10 pr-3 py-2 cursor-pointer flex items-center gap-2 text-[0.85rem] transition-colors select-none {isSelected ? 'bg-blue-50 dark:bg-blue-500/10 border-l-2 border-blue-500 text-blue-700 dark:text-blue-400 font-medium' : 'border-l-2 border-transparent text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-white/5'}"
                    title={p.filename}
                  >
                    <FileText size={14} class={isSelected ? 'text-blue-500' : 'text-gray-400'} />
                    <span class="whitespace-nowrap overflow-hidden text-ellipsis flex-1">
                      {p.label}
                    </span>
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        {/each}
      {/if}
    </div>
  </div>

  <!-- Right Editor -->
  <div class="flex-1 flex flex-col bg-white dark:bg-transparent min-h-0">
    {#if selectedFilename || isCreating}
      <div class="px-5 py-4 border-b border-gray-200 dark:border-white/10 flex justify-between items-center bg-gray-50/50 dark:bg-[#18181b]/50">
        <div class="flex items-center gap-3 flex-1">
          <Code size={18} class="text-gray-400" />
          {#if isCreating}
            <input 
              bind:value={newFilename}
              placeholder="e.g. custom-skill.md"
              class="flex-1 max-w-[300px] px-3 py-1.5 bg-white dark:bg-[#27272a]/50 border border-gray-200 dark:border-white/10 text-gray-900 dark:text-gray-100 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500 text-sm"
            />
          {:else}
            <span class="font-semibold text-gray-800 dark:text-gray-200 text-sm">{selectedFilename}</span>
          {/if}
        </div>
        <div class="flex gap-2">
          {#if !isCreating && selectedFilename}
            <button 
              onclick={() => handleDelete(selectedFilename as string)}
              class="flex items-center gap-1.5 px-3 py-1.5 bg-transparent border border-red-500 text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 rounded-md cursor-pointer text-sm font-medium transition-colors"
            >
              <Trash2 size={14} /> Delete
            </button>
          {/if}
          <button 
            onclick={handleSave}
            class="flex items-center gap-1.5 px-4 py-1.5 bg-blue-600 hover:bg-blue-700 text-white border-none rounded-md cursor-pointer text-sm font-medium transition-colors shadow-sm"
          >
            <Save size={14} /> Save
          </button>
        </div>
      </div>
      <div class="flex-1 flex flex-col p-5 min-h-0">
        <div class="mb-3 flex items-center gap-2 text-[0.8rem] text-yellow-700 dark:text-yellow-500 bg-yellow-50 dark:bg-yellow-900/10 px-3 py-2 rounded-lg border border-yellow-200 dark:border-yellow-900/20">
          <AlertTriangle size={14} class="flex-shrink-0" />
          <span>Playbooks are written in Markdown. Nyxora reads these instructions to execute terminal commands autonomously.</span>
        </div>
        <textarea
          bind:value={editContent}
          class="flex-1 w-full resize-none p-4 font-mono text-[0.85rem] leading-relaxed bg-gray-50 dark:bg-[#18181b]/50 text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-white/10 rounded-lg outline-none focus:ring-1 focus:ring-blue-500 transition-shadow"
          spellcheck="false"
        ></textarea>
      </div>
    {:else}
      <div class="flex-1 flex flex-col items-center justify-center text-gray-400 dark:text-gray-500">
        <BookOpen size={48} class="opacity-20 mb-4" />
        <h3 class="text-lg font-medium text-gray-700 dark:text-gray-300 mb-1">Select a Playbook</h3>
        <p class="text-sm">Or create a new one to teach Nyxora new skills.</p>
      </div>
    {/if}
  </div>
</div>
